[features]
seeds = false

[programs.localnet]
program = "5zBTgkGKfAcsVdTh5gjgW7KyXYzUZc9ZWuukMmbNqYCf"
[program.devnet]
program = "5zBTgkGKfAcsVdTh5gjgW7KyXYzUZc9ZWuukMmbNqYCf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/phongvu/.config/solana/cli/config.yml"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
